### ISSUE TITLE
a bug with the solus theme

### ISSUE THREAD

**Issue by basedcommiedev** [vandalsoul/darkmatter-grub2-theme#17]
Python terminal output:
```
($) Copying the theme directory ...

($) Editing the GRUB file ...

(!) An unexpected error occured while running the script. Installation was unsuccessful ...

(!) ERROR: 'NoneType' object has no attribute 'group'
```

**Comment by vandalsoul** [comment]
Hi @basedcommiedev 
**(1)** Can you tell me which distro you are using?
**(2)** Also can you show me the output of the following command
```
ls /etc | grep "-release"
```

**Comment by medanisjbara** [comment]
I had the same problem. I'm using arch linux, apparently arch has two files ending with "-release" 
```
$ ls -l /etc | grep "release"  #I used "release" instead of "-release" because grep interprets it as a flag even with double quotes 
-rw-r--r-- 1 root root      0 Dec  7 03:41 arch-release
lrwxrwxrwx 1 root root     21 Jan 11 23:09 os-release -> ../usr/lib/os-release
```
for some reason `arch-release` file is an empty file. (totally empty) I don't know if there are other distributions who does the same. but the operating system identification data file is os-release symlink (archlinux uses systemd).
I'm submitting a pull request that checks for the `os-release` first and only does a search if it doesn't exist since searching for that file seems in general [systemd init system stores operating system identification data there](https://www.freedesktop.org/software/systemd/man/os-release.html). if anyone thinks there's a better solution to handle this. I personally think this is the optimal solution because I know how polular systemd is, but I have no idea about other init systems. so if someone thinks there's a better way to handle this please let me know.

**Comment by vandalsoul** [comment]
Hi @medanisjbara 
I haven't used Arch that much so I'm a bit rusty on that. I will update this on my [other theme](https://github.com/vandalsoul/dedsec-grub2-theme) script as well 😇 **(** *you can create a pull request for [it](https://github.com/vandalsoul/dedsec-grub2-theme) also if you like* **)**
And thanks a lot for your effort pal.

**Comment by medanisjbara** [comment]
I believe you can safely close the issue now. I just did the pull request on the other theme.
I'm glad I was able to help ^^
