### ISSUE TITLE
Splash Fonts Jagged/Bumpy - Not Smooth

### ISSUE THREAD

**Issue by 0pLuS0** [vandalsoul/darkmatter-grub2-theme#24]
Hi,

On Slackware 15.0 using grub 2.06, when I'm at the grub splash screen the fonts for the OS are all jagged/bumpy, they are not smooth, sharp, clear...

I tried using two different fonts in Slack, but the results were the same, this is what I tried;

First I tried;

GRUB_FONT=/usr/share/grub/dejavusansmono.pf2

Then I tried;

GRUB_FONT=/usr/share/grub/unifont.pf2

Here's a screen shot, blow it up, and you'll notice the tops/bottoms of the fonts are bumpy and the sides/edges jagged, it looks like this on my box.

![darkmatter](https://user-images.githubusercontent.com/36190223/158715110-cf045fc3-32b5-413e-bb29-49138d69582f.jpg)

Here is a copy of my /etc/default/grub;

[grub.txt](https://github.com/vandalsoul/darkmatter-grub2-theme/files/8278705/grub.txt)

I am also using this theme Tela and the fonts are very sharp/clear/crsip;

https://github.com/vinceliuice/grub2-themes

**Comment by vandalsoul** [comment]
It's actually normal because grub doesn't do a great job dealing with curves and blur effects, so that's why it appears to be pixelated. More smoother the font more pixelated it will be. Read more about that [here](https://github.com/mateosss/matter/issues/38)

From all the fonts I tried the ones that looks not too shabby are Terminus (really crisp) and DejaVu Sans

I'm trying to find a replacement for the current font, hopefully I can find a nice one and it should be fixed in the next update

**Comment by 0pLuS0** [comment]
I'd say, have a look at the thems I posted to see what's going on there...

**Comment by 0pLuS0** [comment]
Yes, their themes, sorry...

I guess then the JetBrains you are using cause this..

Thanks

**Comment by vandalsoul** [comment]
> I guess then the JetBrains you are using causes this..

Yeah, and not only JetBrains if you try to use any Bold or curvy fonts you will see the same issue. I didn't use Terminus and DejaVu Sans because they are just basic common fonts and I wanted to use something different. From all the fonts I tested, JetBrains was the least pixelated one

**Comment by 0pLuS0** [comment]
Hmm, it's very pixelated on my 24" @1920x1080, not clean at all...
