### ISSUE TITLE
关于kali2022

### ISSUE THREAD

**Issue by schen12321** [vandalsoul/darkmatter-grub2-theme#29]
需要修改 `/etc/default/grub.d/kali-themes.cfg`
而不是 `/etc/default/grub`

**Comment by vandalsoul** [comment]
Hi @schen12321 
Yes, I'm aware of the problem that the grub theme isn't working properly in Kali Linux and I think I have tried this method before but didn't work properly. But I have figured out a fix for this issue by working with one of the Kali Linux developers you can find it here : https://github.com/vandalsoul/grub-tweaks#-setting-up-grub-theme-in-kali-linux

Also, I probably won't be adding this method to the installation script since it involves removal of some system files, which I think should be done with the user's consent.
