### ISSUE TITLE
Is there any way to automate the theme selection if running from a bash script?

### ISSUE THREAD

**Issue by fsociety3765** [vandalsoul/darkmatter-grub2-theme#6]

**Comment by vandalsoul** [comment]
Hey there, can you please explain your question a bit. 

The current theme installer is based on python. After installation of a theme if you run it again it will again prompt you with theme style choices, _(GitHub version of the installer only, the installer script in Pling package is just for the installation of your downloaded theme style it won't prompt for anything)_ and if this time you select another theme style the previous installed one will be overwritten

**Comment by fsociety3765** [comment]
Hey,
Sorry for the late reply. I'm writing a bash script that installs Arch Linux. I only ever want to the use the Arch variation and don't want there to be any interactive questions when running the install. Ideally, I just want to run the python script with an argument as to which theme to install so it just does it.
Make sense?

**Comment by vandalsoul** [comment]
> Hey, Sorry for the late reply. I'm writing a bash script that installs Arch Linux. I only ever want to the use the Arch variation and don't want there to be any interactive questions when running the install. Ideally, I just want to run the python script with an argument as to which theme to install so it just does it. Make sense?

Yup, now it makes sense... The installation script found inside the package at [Pling](https://www.pling.com/p/1603282) doesn't ask for any user input, it just looks for the theme folder in cwd and proceeds with installation if found.

What you can do is maybe modify that script using python `argparse` [library](https://docs.python.org/3/library/argparse.html) so that instead of looking at cwd it will take the path as argument.

That should do the job.
